// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskRegister.Infrastructure.Persistence;

#nullable disable

namespace RiskRegister.Infrastructure.Migrations
{
    [DbContext(typeof(RiskRegisterDbContext))]
    partial class RiskRegisterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiskRegister.Core.Entities.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("Impact")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Likelihood")
                        .HasColumnType("tinyint");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("ISNULL(CONVERT(INT, [Likelihood]) * CONVERT(INT, [Impact]), 0)", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Score", "CreatedUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Risks_Score");

                    b.HasIndex("Status", "Score", "CreatedUtc", "Id")
                        .IsDescending(false, true, true, true)
                        .HasDatabaseName("IX_Risks_Status_Score");

                    b.ToTable("Risks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Risks_CreatedUtc", "DATEPART(TZOFFSET, [CreatedUtc]) = 0");

                            t.HasCheckConstraint("CK_Risks_Impact", "[Impact] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Risks_Likelihood", "[Likelihood] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Risks_Owner", "LEN([Owner]) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Risks_Status", "[Status] IN (N'Open', N'Mitigating', N'Accepted', N'Closed')");

                            t.HasCheckConstraint("CK_Risks_Title", "LEN([Title]) BETWEEN 3 AND 200");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
